# Generated by Django 4.0.3 on 2022-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
