# Generated by Django 4.0.3 on 2022-03-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_datecompleted_alter_todo_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
